/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

/**
 *
 * @author erik8460
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    String movietimes[][] = fillData();
    public Test() {
        initComponents();
        
    }

    public String[][] fillData() {

        String data[][] = new String[][]{
            {"Galaxy-10 pm", "Geostorm"},
            {"Galaxy-7 pm", "Kingsman II"},
            {"Galaxy-10 pm", "It"},
            {"Galaxy-7 pm", "Kingsman II"},
            {"Galaxy-8 pm", "Kingsman II"},
            {"Uptown-5 pm", "Jigsaw"},
            {"Galaxy-9 pm", "It"},
            {"Bayfield-8 pm", "Geostorm"},
            {"Galaxy-1 pm", "It"},
            {"Galaxy-3 pm", "Suburbicon"},
            {"Bayfield-5 pm", "Kingsman II"},
            {"Uptown-6 pm", "It"},
            {"Galaxy-7 pm", "It"},
            {"Galaxy-5 pm", "Geostorm"},
            {"Uptown-4 pm", "Suburbicon"},
            {"Bayfield-7 pm", "Kingsman II"},
            {"Bayfield-2 pm", "Kingsman II"},
            {"Galaxy-4 pm", "Geostorm"},
            {"Uptown-10 pm", "Geostorm"},
            {"Galaxy-1 pm", "Happy Death Day"},
            {"Bayfield-5 pm", "It"},
            {"Galaxy-6 pm", "Jigsaw"},
            {"Bayfield-10 pm", "Kingsman II"},
            {"Uptown-5 pm", "Happy Death Day"},
            {"Uptown-3 pm", "Geostorm"},
            {"Uptown-7 pm", "It"},
            {"Galaxy-2 pm", "It"},
            {"Galaxy-9 pm", "Kingsman II"},
            {"Galaxy-8 pm", "It"},
            {"Uptown-4 pm", "Suburbicon"},
            {"Galaxy-5 pm", "Suburbicon"},
            {"Bayfield-8 pm", "It"},
            {"Galaxy-1 pm", "It"},
            {"Uptown-1 pm", "It"},
            {"Uptown-4 pm", "Geostorm"},
            {"Galaxy-4 pm", "It"},
            {"Uptown-1 pm", "Jigsaw"},
            {"Galaxy-6 pm", "Geostorm"},
            {"Bayfield-2 pm", "Jigsaw"},
            {"Galaxy-6 pm", "Suburbicon"},
            {"Uptown-6 pm", "Kingsman II"},
            {"Galaxy-2 pm", "It"},
            {"Uptown-5 pm", "Kingsman II"},
            {"Bayfield-9 pm", "It"},
            {"Bayfield-5 pm", "It"},
            {"Bayfield-1 pm", "Happy Death Day"},
            {"Bayfield-2 pm", "Kingsman II"},
            {"Uptown-1 pm", "Kingsman II"},
            {"Uptown-10 pm", "Kingsman II"},
            {"Uptown-5 pm", "It"}
        };

        return data;
    }
    public String[] getTimes(String[][] t ){
        String times="";
        String movie = txtmovie.getText();
        for (int i = 0; i < t.length; i++) {
            if (movie.equals(t[i][1])){
                times += t[i][0] + ",";
            }
        }
        return times.split(",");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmovie = new javax.swing.JTextField();
        btnget = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter the movie: ");

        btnget.setText("Get Times");
        btnget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetActionPerformed(evt);
            }
        });

        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        txtdisplay.setColumns(20);
        txtdisplay.setRows(5);
        jScrollPane1.setViewportView(txtdisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(txtmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(btnget)
                            .addGap(41, 41, 41)
                            .addComponent(btnclear))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtmovie)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnget)
                    .addComponent(btnclear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetActionPerformed
        txtdisplay.setText("");
        String times[]= getTimes(movietimes);
        if (times[0].equals("")){
            txtdisplay.append("\nERROR: " + txtmovie.getText() + " is an Invalid movie name\n");
            txtmovie.setText("");
            txtmovie.requestFocus();
        }
        else{
            
            txtdisplay.append("\nHere are the movie times for " + txtmovie.getText() + "\n" );
            txtmovie.setText("");
            txtmovie.requestFocus();
            for (int i = 0; i < times.length; i++) {
                txtdisplay.append(times[i] + "\n");
            }
        }
            

    }//GEN-LAST:event_btngetActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        txtdisplay.setText("");
        txtmovie.setText("");
        txtmovie.requestFocus();
    }//GEN-LAST:event_btnclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnget;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtdisplay;
    private javax.swing.JTextField txtmovie;
    // End of variables declaration//GEN-END:variables
}
